### PR TITLE
Better handling titles

### PR DESCRIPTION
**Pull request by ogarbe**
As a subscriber in strava, the system doesn't work as an element subscriber is added to the html

```html
<h2 class="text-title3 text-book marginless">
<div class="badge premium sm" title="Subscriber"></div>
<span class="title">
<a class="minimal" href="/athletes/12121078">Olivier Garbé</a>
–
E-Bike Ride
</span>
</h2>
```

i've replaced document.getElementsByClassName searches by document.title searches which seems to be better working.

But for search, the "|" has to be escaped to be found.

### CODE REVIEW

**Review by nickbeeton — APPROVED** [review]
Looks good, thanks for this!

**Comment by leolimas** [comment]
nice!! I was looking why stopped again :D

**Comment by ogarbe** [comment]
> Looks good, thanks for this!

don't you want to merge it ? ;-)

**Comment by nickbeeton** [comment]
Done now, oops!

**Pull request merged**
